### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by DemoVersion** [mana-ysh/adversarial-object-matching#1]
Dear Hitoshi

I would be greateful if you report precision gained by your models in comparing to reported precision of models in The paper, Have you tested it yet?

Sincerely,
Hesam

**Comment by mana-ysh** [comment]
Hi @DemoVersion

I haven’t tested this implementation yet.
This code is basically for private use while this repository is public.
Therefore, I didn’t plan to exactly reproduce the result in the original paper.
However, I need to test this code with benchmark dataset (bilingual lexicon) and it is important to validate my code. 
if I test, I will report the result as soon as possible.
Thank you for your advice.
